name: Release RPM
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Select package to release'
        required: true
        default: 'yq'
        type: choice
        options:
          - dalitool
          - displaylink
          - evdi
          - jq
          - ringserver
          - slarchive
          - slink2dali
          - slinktool
          - yq
      version:
        description: 'Package release version'
        required: true
        type: string
permissions:
  contents: write
jobs:
  build-release-rpm:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/platformfuzz/image-builder/stream8-rpmbuild:latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: main
      - name: Prepare environment
        run: |
          mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
          cp ./${{ github.event.inputs.package }}/*.spec ./rpmbuild/SPECS/
      - name: Download required sources
        run: |
          cd ./rpmbuild/SOURCES/
          spectool --get-files --all ../SPECS/*.spec
      - name: Install RPM dependencies
        run: |
          cd ./rpmbuild/
          yum-builddep --assumeyes ./SPECS/*.spec
      - name: Build RPM package
        run: |
          cd ./rpmbuild/
          rpmbuild --define "_topdir `pwd`" --ba ./SPECS/*.spec
      - name: Upload artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: "${{ github.event.inputs.package }}"
          path: '**/*.rpm'
          retention-days: 1
      - name: Release
        uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
        with:
          files: |
            **/*.rpm
          draft: false
          fail_on_unmatched_files: true
          generate_release_notes: true
          tag_name: "${{ github.event.inputs.version }}"